server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: merchant
  datasource:
    url: jdbc:mysql://localhost:3306/merchant
    username: root
    password:
