server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: merchant
  cloud:
    config:
      uri: http://localhost:8888
  datasource:
    url: jdbc:mysql://localhost:3306/merchant
    username: root
    password:

